<a href="https://colab.research.google.com/github/edwardsnj/GlyBerta/blob/main/Demonstration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import httpimport, os.path, shutil, sys

!pip install -q transformers

with httpimport.github_repo("edwardsnj", "GlyBerta", ref="main"):
  import glyberta

IUPAC_sequences = "iupacseq.txt"
BASEURL = "https://edwardslab.bmcb.georgetown.edu/~nedwards/dropbox/2tZbwHlPjE/"
if not os.path.exists(IUPAC_sequences):
  !wget {BASEURL}{IUPAC_sequences}
!wc -l {IUPAC_sequences}
!head {IUPAC_sequences}
#

19621 iupacseq.txt
Neu5Gc(?2-?)Neu5Gc(?2-?)Gal(?1-?)Glc(?1-
Gal(?1-4)GlcNAc(?1-?)[Gal(?1-4)GlcNAc(?1-2)]Man(?1-3)[Neu5Ac(?2-6)Gal(?1-4)GlcNAc(?1-2)Man(?1-6)]Man(?1-4)GlcNAc(?1-4)GlcNAc(?1-
Glc(b1-3)Glc(b1-3)Glc(b1-
Glc(b1-4)Glc(b1-4)Glc(b1-4)Glc(b1-
Man(a1-3)[Man(a1-6)]Man(b1-4)GlcNAc(b1-
GlcNAc(b1-2/4)Man(a1-3)[Man(a1-3/6)Man(a1-6)]Man(b1-4)GlcNAc(b1-4)GlcNAc(?1-
Neu5Ac(a2-3/6)Gal(b1-4)GlcNAc(b1-2)Man(a1-3)[Gal(b1-3)Gal(b1-4)GlcNAc(b1-2)[Gal(b1-3)Gal(b1-4)GlcNAc(b1-4)]Man(a1-6)]Man(b1-4)GlcNAc(b1-4)[Fuc(a1-6)]GlcNAc(b1-
Galf(a1-2)Galf(a1-4)Gal(b1-
GalNAc(a1-3)[Fuc(a1-2)]Gal(b1-4)GlcNAc(b1-3)[Neu5Gc(a2-6)]GalNAc(a1-
Gal(b1-3)GalNAc(a1-

In [2]:
!rm -rf glyberta-model
sys.argv = [""] + f"train --data {IUPAC_sequences} --epochs 50 --num_layers 8 --num_heads 8".split()
glyberta.main()

Loaded 19621 sequences from iupacseq.txt
Train: 17659   Test: 1962
Vocabulary size: 128
Test out-of-vocabulary rate: 0/37832 = 0.000%
Model parameters: 6,451,328

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

=== Test-set evaluation ===
  loss            : 0.2139
  perplexity      : 1.2385
  masked accuracy : 92.7612%

Saved model, tokenizer, and test_metrics.json to ./glyberta-model

In [3]:
import json

file_path = '/content/glyberta-model/test_metrics.json'

try:
    with open(file_path, 'r') as f:
        data = json.load(f)
        print(json.dumps(data, indent=2))
except FileNotFoundError:
    print(f"Error: The file {file_path} was not found.")
except json.JSONDecodeError:
    print(f"Error: Could not decode JSON from the file {file_path}.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

{
  "eval_loss": 0.21387231349945068,
  "eval_masked_accuracy": 0.9276115391506898,
  "perplexity": 1.2384645094978852
}

In [7]:
sys.argv = [""] + f"evaluate --output_dir ./glyberta-model --data ./glyberta-model/test.txt".split()
glyberta.main()

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

=== Test-set evaluation ===
  loss            : 6.9597
  perplexity      : 1053.2759
  masked accuracy : 6.3948%